// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hgtkgqijklzkbdnoqioo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhndGtncWlqa2x6a2Jkbm9xaW9vIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM5NTEyMTAsImV4cCI6MjA2OTUyNzIxMH0.QYYYpeE2FkDs9sQZlTWCa2F1Wuwlrecx-Rzx3J2FfoU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});